apiVersion: mail.mailertest.com/v1alpha1
kind: EmailSenderConfig
metadata:
  labels:
    app.kubernetes.io/name: email-operator
    app.kubernetes.io/managed-by: kustomize
  name: emailsenderconfig-sample
spec:
  # TODO(user): Add fields here
